---
- name: Download OneAgent installer in specific version to a custom
    directory with additional OneAgent install parameters. 
  hosts: windows
  collections:
    - dynatrace.oneagent
  # credentials.yml file contains oneagent_environment_url and
  # oneagent_paas_token variables that needs to be stored securely
  vars_files:
    - credentials.yml
  vars:
    oneagent_installer_arch: x86
    oneagent_download_dir: D:\softwares
    oneagent_version: "latest"
    oneagent_package_state: present
    oneagent_install_args:
      - --set-host-group=POC
      - --set-host-name={{ ansible_fqdn }}
      - --set-host-tag=poc
      - --set-host-property=contact="mmse1cnc@mckesson.com"
  tasks:
    - import_role:
        name: oneagent